name: QuickDig
main: com.dustinschreiber.QuickDig.QuickDig
version: 1.0
commands:
   quick:
      description: Enables/Disables QuickDig
      usage: /quick - Enables/Disables QuickDig
      permission: quickdig.use
      permission-message: You can't use QuickDig